---
title: "KOD - projekt MDP"
author: "Eliza Muca"
date: "2024-11-30"
output:
  pdf_document: default
  word_document: default
---

```{r}
#1. Tworzenie iloczynu kartezjańskiego

##a)
options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages(c("ncdf4", "dplyr", "sp", "ggplot2"))
library(ncdf4)
library(dplyr)
library(sp)
library(ggplot2)
##b)
nc <- nc_open("C:/Users/48792/Desktop/AGH/SEMESTR_5/MDP/lab1/gebco_2024.nc")
#c)
print(nc)

##d)
elev <- ncvar_get(nc, "elevation")
lon <- ncvar_get(nc, "lon")
lat <- ncvar_get(nc, "lat")
lat

##e)
length(lat) * length(lon) == length(elev)
#zgadza się,  iloczyn długości (length) wektorów długości i szerokości geograficznej
#równa się długości (length) macierzy wysokości elev

##f)
cartesian_product<- expand.grid(lon,lat)
#cartesian_product<- expand.grid(lat,lon) 
# W sensie matematycznym obie wersje są poprawne, ponieważ iloczyn kartezjański jest
#przemienny, natomiast w naszym przypadku zgodnie z ostatecznymi zaleceniami i tym, że nasza
#ramka ma zawierac kolejno szerokość, długość, wysokość, uważam, że należy wybrać wersję powyższą
#cartesian_product<- expand.grid(lat,lon)

##g)
cartesian_product<- dplyr::mutate(cartesian_product, c(elev) )

##h)
colnames(cartesian_product)<-c("x","y", "z")


##i)
coordinates(cartesian_product) <- c("x", "y")

##j)
proj4string(cartesian_product) <- CRS("+proj=longlat +datum=WGS84")

##k)
cartesian_product <- spTransform(cartesian_product,
                                 CRS("EPSG:32644"))
cartesian_product<-as.data.frame(cartesian_product)
cartesian_product<-dplyr::mutate(cartesian_product,
                                 id=1:nrow(cartesian_product))
summary(cartesian_product)

##l)
##cartesian_product <- dplyr::filter(cartesian_product, y < 1743019 & y > 1644731 & x > 424924 & x < 515463)
##tego nie potrzebuję, bo mam juz dobry rozmiar terenu

##m)
cartesian_product<-dplyr::select(cartesian_product, c(3,2,1,4))
write.table(x=cartesian_product, file = "gebco2024.txt", sep=" ",
            row.names = F, col.names = F )


write.csv(cartesian_product, "C:/Users/48792/Desktop/AGH/SEMESTR_5/MDP/cartesian_product.csv", row.names = FALSE)

# 2. Odflitrowanie danych, gdzie dip_dir=x
file <- read.csv("C:/Users/48792/Desktop/AGH/SEMESTR_5/MDP/lab3/muca/muca_output_0.txt",sep=";")
df1 <- file[!(file$Dip_dir=="x"),]
df1 <- transform(df1, Dip_dir = as.numeric(Dip_dir))
write.table(x=df1, file = "muca_output_0-filtred.txt", sep = ";",row.names = F)

```

```{r}
# 3. Usuwanie anomalii brzegowych, z każdej strony 2%


file = read.csv("muca_output_0-filtred.txt",sep=";")
minX = min(file$X_C)
maxX = max(file$X_C)
minY = min(file$Y_C)
maxY = max(file$Y_C)
df = dplyr::filter(file, X_C >= minX + 0.02*(maxX - minX))
df = dplyr::filter(df, X_C <= maxX - 0.02*(maxX - minX))
df = dplyr::filter(df, Y_C >= minY + 0.02*(maxY - minY))
df = dplyr::filter(df, Y_C <= maxY - 0.02*(maxY - minY))
write.table(x=df, file = "muca_output_0_filtred_c.txt", sep = ";",row.names = F)

```

```{r}

#4. Ustalanie odpowiedniej liczby klastrów dla algorytmu k-średnich

file = read.csv("C:/Users/48792/Desktop/muca_output_0_filtred_cutted.txt",sep=";")
nrow(file)

wss <- sapply(1:10, function(k) {
  kmeans(as.matrix(dplyr::select(file, c("X_N", "Y_N", "Z_N"))), centers = k, nstart = 40)$tot.withinss
})


plot(1:10, wss, type = "b", pch = 19, col = "darkblue", lwd = 2, 
     xlab = "Liczba klastrów (k)", 
     ylab = "Suma kwadratów odległości (WSS)",
     main = "Optymalna liczba klastrów dla danych \nX_N, Y_N, Z_N – metoda łokcia",
     cex.axis = 1.2, cex.lab = 1.4, cex.main = 1.5)

ss <- sapply(1:10, function(k) {
    kmeans(as.matrix(dplyr::select(file, c("X_D", "Y_D", "Z_D"))), centers = k, nstart = 50)$tot.withinss
  })


 plot(1:10, ss, type = "b", pch = 19, col = "darkblue", lwd = 2, 
       xlab = "Liczba klastrów (k)", 
       ylab = "Suma kwadratów odległości (WSS)",
       main = "Optymalna liczba klastrów dla danych \n X_D, Y_D, Z_D – metoda łokcia",
       cex.axis = 1.2, cex.lab = 1.4, cex.main = 1.5)
 
 
```

```{r}
 
#5. Grupowanie do Stereonetu - 3 klastry
 
 
## Grupowanie z trzema klastrami
grupowanie_normals <- kmeans(as.matrix(dplyr::select(file, c("X_N", "Y_N", "Z_N"))), 
                             centers = 3, nstart = 51, iter.max = 100000, algorithm = "Lloyd")

grupowanie_dip <- kmeans(as.matrix(dplyr::select(file, c("X_D", "Y_D", "Z_D"))), 
                         centers = 3, nstart = 51, iter.max = 100000, algorithm = "Lloyd")

## Przypisanie klastrów do danych
file1 <- file
file2 <- file
file1$clustering <- grupowanie_normals$cluster
file2$clustering <- grupowanie_dip$cluster

## Losowa próbka dla wizualizacji
set.seed(35)
file1 <- sample_n(file1, 10000)
file2 <- sample_n(file2, 10000)

## Filtrowanie danych dla każdego klastra dla wektorów normalnych
df1_normals <- dplyr::filter(file1, clustering == 1)[c("Dip_dir", "Dip_ang")]
df2_normals <- dplyr::filter(file1, clustering == 2)[c("Dip_dir", "Dip_ang")]
df3_normals <- dplyr::filter(file1, clustering == 3)[c("Dip_dir", "Dip_ang")]

## Filtrowanie danych dla każdego klastra dla wektorów leżących
df1_dip <- dplyr::filter(file2, clustering == 1)[c("Dip_dir", "Dip_ang")]
df2_dip <- dplyr::filter(file2, clustering == 2)[c("Dip_dir", "Dip_ang")]
df3_dip <- dplyr::filter(file2, clustering == 3)[c("Dip_dir", "Dip_ang")]

## Zapis wyników dla wektorów normalnych
write.table(x = df1_normals, file = "C:/Users/48792/Desktop/projekt_mdp/dfn_1_normals.txt", sep = ",", row.names = F, col.names = F)
write.table(x = df2_normals, file = "C:/Users/48792/Desktop/projekt_mdp/dfn_2_normals.txt", sep = ",", row.names = F, col.names = F)
write.table(x = df3_normals, file = "C:/Users/48792/Desktop/projekt_mdp/dfn_3_normals.txt", sep = ",", row.names = F, col.names = F)

## Zapis dla wektorów leżących
write.table(x = df1_dip, file = "C:/Users/48792/Desktop/projekt_mdp/dfn_1_dip.txt", sep = ",", row.names = F, col.names = F)
write.table(x = df2_dip, file = "C:/Users/48792/Desktop/projekt_mdp/dfn_2_dip.txt", sep = ",", row.names = F, col.names = F)
write.table(x = df3_dip, file = "C:/Users/48792/Desktop/projekt_mdp/dfn_3_dip.txt", sep = ",", row.names = F, col.names = F)


ggplot(file1) +
  geom_point(aes(Y_C, X_C, colour = factor(clustering)), size = 1, alpha = 0.8) +
  scale_colour_manual(values = c("#FF6F61", "#6B5B95", "#88B04B")) + 
  labs(title = "Mapa grupowania trójkątów - Wektory normalne",
       subtitle = "Grupowanie dla danych X_N, Y_N, Z_N",
       x = "Y_C", 
       y = "X_C", 
       colour = "Klastry") +
  theme_minimal() +
  theme(plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 9))


ggplot(file2) +
  geom_point(aes(Y_C, X_C, colour = factor(clustering)), size = 1, alpha = 0.8) +
  scale_colour_manual(values = c("#F7CAC9", "#92A8D1", "#034F84")) + 
       labs(title = "Mapa grupowania trójkątów - Wektory leżące",
            subtitle = "Grupowanie dla danych X_D, Y_D, Z_D",
            x = "Y_C", 
            y = "X_C", 
            colour = "Klastry") +
         theme_minimal() +
         theme(plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
               plot.subtitle = element_text(size = 12, hjust = 0.5),
               axis.text = element_text(size = 10),
               axis.title = element_text(size = 12),
               legend.title = element_text(size = 10),
               legend.text = element_text(size = 9))



```


```{r}
#6. Wyznaczanie środków skupień 

calculate_norm <- function(x) sqrt(sum(x^2))

normalize_cluster_centers <- function(centers) {
  t(apply(centers, 1, function(row) row / calculate_norm(row)))
}

calculate_orientations <- function(normalized_centers) {
  orientations <- t(apply(normalized_centers, 1, function(v) {
    
    dip_ang = acos(v[3]) * (180 / pi) - 90
    if (dip_ang < 0) dip_ang = dip_ang + 90
    
    
    dip_dir = atan2(v[2], v[1]) * (180 / pi)
    if (dip_dir < 0) dip_dir = dip_dir + 360
    
    c(Dip_ang = dip_ang, Dip_dir = dip_dir)
  }))
  
  return(as.data.frame(orientations))
}

get_cluster_orientations <- function(kmeans_result) {
  centers <- kmeans_result$centers
  normalized_centers <- normalize_cluster_centers(centers)
  orientations <- calculate_orientations(normalized_centers)
  return(orientations)
}

orientations_normals <- get_cluster_orientations(grupowanie_normals)
orientations_dip <- get_cluster_orientations(grupowanie_dip)

print(orientations_normals)
print(orientations_dip)

orientations_normals= orientations_normals[, c("Dip_dir.Y_N", "Dip_ang.Z_N")]
orientations_dip=orientations_dip[, c("Dip_dir.Y_D", "Dip_ang.Z_D")]


for (i in 1:nrow(orientations_normals)) {
  file_name <- paste0("C:/Users/48792/Desktop/projekt_mdp/nor_cluster_", i, ".txt")
  write.table(orientations_normals[i, , drop = FALSE], file = file_name, sep = ",", row.names = FALSE, col.names = FALSE)
}

for (i in 1:nrow(orientations_dip)) {
  file_name <- paste0("C:/Users/48792/Desktop/projekt_mdp/dip_cluster_", i, ".txt")
  write.table(orientations_dip[i, , drop = FALSE], file = file_name, sep = ",", row.names = FALSE, col.names = FALSE)
}


```

